/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Vocabulary = IDL.Record({
  'meaning' : IDL.Text,
  'word' : IDL.Text,
  'example' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Progress = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Nat),
  'lessonsCompleted' : IDL.Vec(IDL.Nat),
  'vocabularyLearned' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addLesson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addVocabulary' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllVocabulary' : IDL.Func([], [IDL.Vec(Vocabulary)], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getProgress' : IDL.Func([IDL.Text], [Progress], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'conversation' : IDL.Vec(Message),
          'response' : IDL.Text,
        }),
      ],
      [],
    ),
  'updateProgress' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Vocabulary = IDL.Record({
    'meaning' : IDL.Text,
    'word' : IDL.Text,
    'example' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Progress = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Nat),
    'lessonsCompleted' : IDL.Vec(IDL.Nat),
    'vocabularyLearned' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addLesson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addVocabulary' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllVocabulary' : IDL.Func([], [IDL.Vec(Vocabulary)], ['query']),
    'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getProgress' : IDL.Func([IDL.Text], [Progress], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'conversation' : IDL.Vec(Message),
            'response' : IDL.Text,
          }),
        ],
        [],
      ),
    'updateProgress' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };